glslc g_pass.vert -o g_pass.vert.spv
glslc g_pass.frag -o g_pass.frag.spv
glslc depth_copy.frag -o depth_copy.frag.spv
glslc lightning.frag -o lightning.frag.spv
glslc blend.frag -o blend.frag.spv
glslc blend.vert -o blend.vert.spv
glslc coord_system.vert -o coord_system.vert.spv
glslc coord_system.frag -o coord_system.frag.spv
glslc present.vert -o present.vert.spv
glslc present.frag -o present.frag.spv
glslc skybox.vert -o skybox.vert.spv
glslc skybox.frag -o skybox.frag.spv
glslc shadow_map.vert -o shadow_map.vert.spv
glslc equirect_to_cubemap.vert -o equirect_to_cubemap.vert.spv
glslc equirect_to_cubemap.frag -o equirect_to_cubemap.frag.spv